FROM arm64v8/php:7.2-apache

ENV APACHE_DOCUMENT_ROOT /home/bitrix/www
WORKDIR /home/bitrix/www

RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf
RUN sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf

# RUN mv "$PHP_INI_DIR/php.ini-development" "$PHP_INI_DIR/php.ini"
RUN apt-get clean all && apt-get update && apt-get dist-upgrade -y
RUN pecl channel-update pear.php.net

RUN apt-get update -y && apt-get upgrade -y && apt-get install apt-utils -y
RUN apt-get install -y libmemcached-dev
RUN apt-get install -y libsodium-dev
RUN apt-get install -y zip unzip vim dialog
RUN apt-get install -y libhashkit2 zlib1g-dev libzip-dev
RUN apt-get install -y wget
RUN apt-get install -y libpq-dev
RUN apt-get install -y libldap2-dev
RUN apt-get install -y libldap2-dev
RUN apt-get install -y git
RUN apt-get install -y mariadb-client
RUN apt-get install -y default-mysql-client
RUN apt-get install -y memcached

# RUN pecl install redis
RUN pecl install memcache memcached
RUN pecl install -f libsodium
RUN pecl install pcov

RUN cd /usr/local/etc/php/conf.d/ && echo "extension=memcache.so" > 02-memcache.ini
RUN cd /usr/local/etc/php/conf.d/ && echo "extension=memcached.so" > 02-memcached.ini
RUN cd /usr/local/etc/php/conf.d/ && echo "extension=pcov.so" > 05-pcov.ini
RUN cd /usr/local/etc/php/conf.d/ && echo "short_open_tag=on" > short-tag.ini

RUN docker-php-ext-install pdo_mysql mysqli
RUN docker-php-ext-install zip
RUN docker-php-ext-install sockets
RUN docker-php-ext-install bcmath
RUN docker-php-ext-install pcntl
RUN docker-php-ext-install exif

RUN a2enmod headers
RUN a2enmod rewrite

RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections

RUN curl -sS https://getcomposer.org/installer -o composer-setup.php
RUN php composer-setup.php --install-dir=/usr/local/bin --filename=composer
# COPY ./auth.json /root/.composer/auth.json